### ISSUE TITLE
Select SMF and UPF based on S-NASSI 。 SCP Mode D is not working

### ISSUE THREAD

**Issue by caoyousheng** [s5uishida/open5gs_5gc_ueransim_snssai_upf_sample_config#3]
v2.6.0 open5gs.
I  replicate your sample configuration, but it's not work , 
By analyzing the pcap,I guess is that The AMF did not perform the SMF selection operation, and SCP only supports service discovery, but not service selection.

so i change SCP MODE D to MODE C  ,and then it worked.
amf.yaml Add the following configuration:
```
    discovery:
      delegated: no
nrf:
    sbi:
      - addr:
          - 172.22.0.12
        port: 7777
```
Sorry if I'm wrong !
[Select UPF based on S-NSSAI.zip](https://github.com/s5uishida/open5gs_5gc_ueransim_snssai_upf_sample_config/files/10764756/Select.UPF.based.on.S-NSSAI.zip)
